# Generated by Django 3.2.11 on 2022-01-08 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cCode', models.CharField(max_length=4, verbose_name='課程代碼')),
                ('cName', models.CharField(max_length=50, verbose_name='課程中文名稱')),
                ('cEn_name', models.CharField(max_length=100, null=True, verbose_name='課程英文名稱')),
                ('cProfessor', models.CharField(max_length=50, verbose_name='課程教師')),
                ('cDept', models.CharField(max_length=50, verbose_name='課程系所')),
                ('cType', models.CharField(max_length=2, verbose_name='課程類別')),
                ('cCredit', models.DecimalField(decimal_places=0, default=0, max_digits=1, verbose_name='課程學分')),
                ('cLang', models.CharField(max_length=2, verbose_name='課程語言')),
                ('cCool', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='涼')),
                ('cSweet', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='甜')),
                ('cFun', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='有趣')),
                ('cLearn', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='學習')),
                ('cJoin', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='參與')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dDept', models.CharField(max_length=50, unique=True, verbose_name='系所名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pDept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.department')),
                ('pUID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mContent', models.CharField(max_length=1000, verbose_name='評論內容')),
                ('mCool', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='涼')),
                ('mSweet', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='甜')),
                ('mFun', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='有趣')),
                ('mLearn', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='學習')),
                ('mjoin', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='參與')),
                ('mLasttime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最後修改時間')),
                ('mCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.class')),
                ('mUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mUID', 'mCID')},
            },
        ),
    ]
