# Generated by Django 3.2.11 on 2022-01-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20220110_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dDept',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='系所名稱'),
        ),
    ]
