# Generated by Django 3.2.11 on 2022-01-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_department_ddept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dDept',
            field=models.CharField(max_length=50, unique=True, verbose_name='系所名稱'),
        ),
    ]
