# Generated by Django 3.2.11 on 2022-01-15 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0009_alter_department_ddept'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='cFollow',
            field=models.IntegerField(default=0, verbose_name='追蹤數'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.class')),
                ('fUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('fUID', 'fCID')},
            },
        ),
    ]
