# Generated by Django 3.2.11 on 2022-01-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20220115_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='fLasttime',
            field=models.DateTimeField(auto_now=True, verbose_name='最後追蹤時間'),
        ),
    ]
