# Generated by Django 3.2.11 on 2022-01-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_follow_flasttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='cCredit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1, null=True, verbose_name='課程學分'),
        ),
        migrations.AlterField(
            model_name='class',
            name='cDept',
            field=models.CharField(max_length=50, null=True, verbose_name='課程系所'),
        ),
        migrations.AlterField(
            model_name='class',
            name='cLang',
            field=models.CharField(max_length=5, null=True, verbose_name='課程語言'),
        ),
        migrations.AlterField(
            model_name='class',
            name='cProfessor',
            field=models.CharField(max_length=50, null=True, verbose_name='課程教師'),
        ),
        migrations.AlterField(
            model_name='class',
            name='cType',
            field=models.CharField(max_length=5, null=True, verbose_name='課程類別'),
        ),
    ]
